version: "3"
services:
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: movie_characters_api
    ports:
      - "5432:5432"

  movie_characters_api:
    image: movie-characters-api
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    command: java -jar -Dspring.profiles.active=dev movie_characters_api-0.0.1-SNAPSHOT.jar
