version: '3'
services:
  pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "movie_characters_api"
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - my-network

  api:
    build:
      context: .
      args:
        PROJECT-NAME: movie_characters_api
    entrypoint: "java -jar movie_characters_api-0.0.1-SNAPSHOT.jar"
    ports:
      - "127.0.0.1:8088:8080"
    depends_on:
      - pg
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
