server:
  servlet:
    context-path: "/api"
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/movie_characters_api
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create # Change to "create" for first time use to generate database schema then change to "update"
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: 50
        session_factory:
          name: com.example.SessionFactory
          allow_create_outside_transaction: true

  banner:
    location: classpath:/path/to/banner/banner.txt
  main:
    allow-bean-definition-overriding: true # If you want to allow overriding of beans
  sql:
    init:
      mode: never


