server:
  servlet:
    context-path: "/api"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_characters_api
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Change to "create" for first time use to generate database schema then change to "update"
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#  spring:
#    banner:
#      location: classpath:/path/to/banner/banner.txt
  main:
    allow-bean-definition-overriding: true # If you want to allow overriding of beans


