server:
  servlet:
    context-path: "/api"
spring:
  datasource:
    url: jdbc:postgresql://pg:5432/movie_characters_api
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update # Change to "create" for first time use to generate database schema then change to "update"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  main:
    allow-bean-definition-overriding: true # If you want to allow overriding of beans
  sql:
    init:
      mode: never


