server:
  port: 8080

logging:
  level:
    root: INFO
    com:
      experis:
        movie_characters_api: DEBUG
    org:
      springframework:
        boot:
          autoconfigure: INFO
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/movie_characters_api
  jpa:
    hibernate:
      ddl-auto: update # NEVER CHANGE TO CREATE_DROP OR CREATE IN PRODUCTION. update can add, but never remove tables and columns
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    tomcat:
#      max-wait: 20000
#      test-on-borrow: true
#      test-while-idle: true
#      validation-query: SELECT 1
#      validation-query-timeout: 1000
#      validation-interval: 1000
#